

BF_DIR = ~/Workspace/Projects/Personal/BattleFactory

PE_DIR = $(BF_DIR)/PokemonEntry
PD_DIR = $(BF_DIR)/Pokedex
GD_DIR = $(BF_DIR)/GlobalDestroyer


INC_DIR = `pwd`

FLAGS = -I$(INC_DIR) -c -Wall

PETester: $(PE_DIR)/PokemonEntry.o $(PE_DIR)/PokemonStats.o $(PE_DIR)/Typing.o $(PE_DIR)/PokemonEntryTestDriver.o $(PD_DIR)/Pokedex.o $(GD_DIR)/GlobalDestroyer.o $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o 
	gcc -o PETester $(PE_DIR)/PokemonEntry.o $(PE_DIR)/PokemonStats.o $(PE_DIR)/Typing.o $(PE_DIR)/PokemonEntryTestDriver.o $(PD_DIR)/Pokedex.o $(GD_DIR)/GlobalDestroyer.o $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o 

PokeMoveSetTester: $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o $(PE_DIR)/PokemonMoveTester.o $(GD_DIR)/GlobalDestroyer.o 
	gcc -o PokeMoveSetTester $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o $(PE_DIR)/PokemonMoveTester.o $(GD_DIR)/GlobalDestroyer.o $(PE_DIR)/PokemonEntry.o $(PE_DIR)/PokemonStats.o $(PE_DIR)/Typing.o $(PD_DIR)/Pokedex.o

$(PE_DIR)/PokemonEntry.o: $(PE_DIR)/PokemonEntry.c $(PE_DIR)/PokemonEntry.h $(PE_DIR)/PokemonStats.h $(PE_DIR)/Typing.h $(GD_DIR)/GlobalDestroyer.h
	gcc $(FLAGS) $(PE_DIR)/PokemonEntry.c -o $(PE_DIR)/PokemonEntry.o

$(PE_DIR)/PokemonStats.o: $(PE_DIR)/PokemonStats.c $(PE_DIR)/PokemonStats.h $(GD_DIR)/GlobalDestroyer.h
	gcc $(FLAGS) $(PE_DIR)/PokemonStats.c -o $(PE_DIR)/PokemonStats.o

$(PE_DIR)/Typing.o: $(PE_DIR)/Typing.c $(PE_DIR)/Typing.h $(GD_DIR)/GlobalDestroyer.h
	gcc $(FLAGS) $(PE_DIR)/Typing.c -o $(PE_DIR)/Typing.o

$(PE_DIR)/PokemonMoveSet.o: $(PE_DIR)/PokemonMoveSet.c $(PE_DIR)/PokemonMoveSet.h $(PE_DIR)/PokemonMove.h $(GD_DIR)/GlobalDestroyer.h
	gcc $(FLAGS) $(PE_DIR)/PokemonMoveSet.c -o $(PE_DIR)/PokemonMoveSet.o

$(PE_DIR)/PokemonMove.o: $(PE_DIR)/PokemonMove.c $(PE_DIR)/PokemonMove.h $(GD_DIR)/GlobalDestroyer.h
	gcc $(FLAGS) $(PE_DIR)/PokemonMove.c -o $(PE_DIR)/PokemonMove.o

$(PE_DIR)/PokemonEntryTestDriver.o: $(PE_DIR)/PokemonEntryTestDriver.c $(PE_DIR)/PokemonEntryTestDriver.h $(PE_DIR)/PokemonEntry.h $(PE_DIR)/Typing.h
	gcc $(FLAGS) $(PE_DIR)/PokemonEntryTestDriver.c -o $(PE_DIR)/PokemonEntryTestDriver.o

$(PD_DIR)/Pokedex.o: $(PD_DIR)/Pokedex.c $(PD_DIR)/Pokedex.h $(GD_DIR)/GlobalDestroyer.h $(PE_DIR)/Typing.h
	gcc $(FLAGS) $(PD_DIR)/Pokedex.c -o $(PD_DIR)/Pokedex.o

$(GD_DIR)/GlobalDestroyer.o: $(GD_DIR)/GlobalDestroyer.c $(GD_DIR)/GlobalDestroyer.h $(PE_DIR)/PokemonEntry.h $(PD_DIR)/Pokedex.h
	gcc $(FLAGS) $(GD_DIR)/GlobalDestroyer.c -o $(GD_DIR)/GlobalDestroyer.o



clean: 
	rm */*.o *.o *~ PETester PokeMoveSetTester







