


BF_DIR = $(shell pwd)

PE_DIR = $(BF_DIR)/PokemonEntry
PD_DIR = $(BF_DIR)/Pokedex
GD_DIR = $(BF_DIR)/GlobalDestroyer
SU_DIR = $(BF_DIR)/BF_Special_Util
TG_DIR = $(BF_DIR)/TagGenerator
SC_DIR = $(BF_DIR)/SpecialConstants
RD_DIR = $(BF_DIR)/RetrieveData
BS_DIR = $(BF_DIR)/BattleSimulation
MT_DIR = $(BF_DIR)/MoveTable

INC_DIR = $(shell pwd)

FLAGS = -I$(INC_DIR) -c -Wall

GLOBAL_DESTROYER_OBJS = $(BS_DIR)/BattleSimulation.o $(PE_DIR)/PokemonEntry.o $(PD_DIR)/Pokedex.o $(PE_DIR)/PokemonStats.o $(PE_DIR)/Typing.o $(GD_DIR)/GlobalDestroyer.o $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o $(RD_DIR)/RetrievePokemon.o $(SU_DIR)/Special_Util.o

MTTester: $(MT_DIR)/MoveTable.o $(MT_DIR)/MoveTableTester.o $(GLOBAL_DESTROYER_OBJS)
	gcc -o MTTester $(MT_DIR)/MoveTable.o $(MT_DIR)/MoveTableTester.o $(GLOBAL_DESTROYER_OBJS) 

BSTester: $(PE_DIR)/PokemonEntry.o $(PE_DIR)/PokemonStats.o $(PE_DIR)/Typing.o $(PD_DIR)/Pokedex.o $(GD_DIR)/GlobalDestroyer.o $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o $(SU_DIR)/Special_Util.o $(RD_DIR)/RetrievePokemon.o $(BS_DIR)/BattleSimulation.o $(BS_DIR)/BattleSimTester.o
	gcc -o BSTester $(PE_DIR)/PokemonEntry.o $(PE_DIR)/PokemonStats.o $(PE_DIR)/Typing.o $(PD_DIR)/Pokedex.o $(GD_DIR)/GlobalDestroyer.o $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o $(SU_DIR)/Special_Util.o $(RD_DIR)/RetrievePokemon.o $(BS_DIR)/BattleSimulation.o $(BS_DIR)/BattleSimTester.o

RDTester: $(GLOBAL_DESTROYER_OBJS) $(RD_DIR)/RetrieveTester.o 
	gcc -o RDTester $(GLOBAL_DESTROYER_OBJS) $(RD_DIR)/RetrieveTester.o 

PETester: $(PE_DIR)/PokemonEntry.o $(PE_DIR)/PokemonStats.o $(PE_DIR)/Typing.o $(PE_DIR)/PokemonEntryTestDriver.o $(PD_DIR)/Pokedex.o $(GD_DIR)/GlobalDestroyer.o $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o $(SU_DIR)/Special_Util.o
	gcc -o PETester $(PE_DIR)/PokemonEntry.o $(PE_DIR)/PokemonStats.o $(PE_DIR)/Typing.o $(PE_DIR)/PokemonEntryTestDriver.o $(PD_DIR)/Pokedex.o $(GD_DIR)/GlobalDestroyer.o $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o $(SU_DIR)/Special_Util.o

PokedexTester: $(PE_DIR)/PokemonEntry.o $(PE_DIR)/PokemonStats.o $(PE_DIR)/Typing.o $(PD_DIR)/PokedexTesterMain.o $(PD_DIR)/Pokedex.o $(GD_DIR)/GlobalDestroyer.o $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o $(SU_DIR)/Special_Util.o 
	gcc -o PokedexTester $(PE_DIR)/PokemonEntry.o $(PE_DIR)/PokemonStats.o $(PE_DIR)/Typing.o $(PD_DIR)/PokedexTesterMain.o $(PD_DIR)/Pokedex.o $(GD_DIR)/GlobalDestroyer.o $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o $(SU_DIR)/Special_Util.o

PokeMoveSetTester: $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o $(PE_DIR)/PokemonMoveTester.o $(GD_DIR)/GlobalDestroyer.o $(SU_DIR)/Special_Util.o
	gcc -o PokeMoveSetTester $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o $(PE_DIR)/PokemonMoveTester.o $(GD_DIR)/GlobalDestroyer.o $(PE_DIR)/PokemonEntry.o $(PE_DIR)/PokemonStats.o $(PE_DIR)/Typing.o $(PD_DIR)/Pokedex.o$(SU_DIR)/Special_Util.o

TagGenTester: $(TG_DIR)/TagGenTester.o $(TG_DIR)/FillDataFiles.o $(SU_DIR)/Special_Util.o $(GD_DIR)/GlobalDestroyer.o $(PE_DIR)/PokemonEntry.o $(PE_DIR)/PokemonStats.o $(PE_DIR)/Typing.o $(PD_DIR)/Pokedex.o $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o
	gcc -o TagGenTester $(TG_DIR)/TagGenTester.o $(TG_DIR)/FillDataFiles.o $(SU_DIR)/Special_Util.o $(GD_DIR)/GlobalDestroyer.o $(PE_DIR)/PokemonEntry.o $(PE_DIR)/PokemonStats.o $(PE_DIR)/Typing.o $(PD_DIR)/Pokedex.o $(PE_DIR)/PokemonMove.o $(PE_DIR)/PokemonMoveSet.o

$(PE_DIR)/PokemonEntry.o: $(PE_DIR)/PokemonEntry.c $(PE_DIR)/PokemonEntry.h $(PE_DIR)/PokemonStats.h $(PE_DIR)/Typing.h $(GD_DIR)/GlobalDestroyer.h $(SC_DIR)/SpecialConstants.h
	gcc $(FLAGS) $(PE_DIR)/PokemonEntry.c -o $(PE_DIR)/PokemonEntry.o

$(PE_DIR)/PokemonStats.o: $(PE_DIR)/PokemonStats.c $(PE_DIR)/PokemonStats.h $(GD_DIR)/GlobalDestroyer.h
	gcc $(FLAGS) $(PE_DIR)/PokemonStats.c -o $(PE_DIR)/PokemonStats.o

$(PE_DIR)/Typing.o: $(PE_DIR)/Typing.c $(PE_DIR)/Typing.h $(GD_DIR)/GlobalDestroyer.h $(SC_DIR)/SpecialConstants.h
	gcc $(FLAGS) $(PE_DIR)/Typing.c -o $(PE_DIR)/Typing.o

$(PE_DIR)/PokemonMoveSet.o: $(PE_DIR)/PokemonMoveSet.c $(PE_DIR)/PokemonMoveSet.h $(PE_DIR)/PokemonMove.h $(GD_DIR)/GlobalDestroyer.h
	gcc $(FLAGS) $(PE_DIR)/PokemonMoveSet.c -o $(PE_DIR)/PokemonMoveSet.o

$(PE_DIR)/PokemonMove.o: $(PE_DIR)/PokemonMove.c $(PE_DIR)/PokemonMove.h $(GD_DIR)/GlobalDestroyer.h $(SC_DIR)/SpecialConstants.h
	gcc $(FLAGS) $(PE_DIR)/PokemonMove.c -o $(PE_DIR)/PokemonMove.o 

$(PE_DIR)/PokemonEntryTestDriver.o: $(PE_DIR)/PokemonEntryTestDriver.c $(PE_DIR)/PokemonEntryTestDriver.h $(PE_DIR)/PokemonEntry.h $(PE_DIR)/Typing.h
	gcc $(FLAGS) $(PE_DIR)/PokemonEntryTestDriver.c -o $(PE_DIR)/PokemonEntryTestDriver.o

$(PD_DIR)/PokedexTesterMain.o: $(PD_DIR)/PokedexTesterMain.c $(GD_DIR)/GlobalDestroyer.h $(PD_DIR)/Pokedex.h
	gcc $(FLAGS) $(PD_DIR)/PokedexTesterMain.c -o $(PD_DIR)/PokedexTesterMain.o

$(PD_DIR)/Pokedex.o: $(PD_DIR)/Pokedex.c $(PD_DIR)/Pokedex.h $(GD_DIR)/GlobalDestroyer.h $(PE_DIR)/Typing.h $(SU_DIR)/Special_Util.h $(SC_DIR)/SpecialConstants.h
	gcc $(FLAGS) $(PD_DIR)/Pokedex.c -o $(PD_DIR)/Pokedex.o

$(GD_DIR)/GlobalDestroyer.o: $(GD_DIR)/GlobalDestroyer.c $(GD_DIR)/GlobalDestroyer.h $(PE_DIR)/PokemonEntry.h $(PD_DIR)/Pokedex.h $(BS_DIR)/BattleSimulation.h
	gcc $(FLAGS) $(GD_DIR)/GlobalDestroyer.c -o $(GD_DIR)/GlobalDestroyer.o

$(SU_DIR)/Special_Util.o: $(SU_DIR)/Special_Util.c $(GD_DIR)/GlobalDestroyer.h $(SU_DIR)/Special_Util.h $(SC_DIR)/SpecialConstants.h
	gcc $(FLAGS) $(SU_DIR)/Special_Util.c -o $(SU_DIR)/Special_Util.o

$(TG_DIR)/FillDataFiles.o: $(TG_DIR)/FillDataFiles.c $(TG_DIR)/FillDataFiles.h $(SU_DIR)/Special_Util.h $(SC_DIR)/SpecialConstants.h
	gcc $(FLAGS) $(TG_DIR)/FillDataFiles.c -o $(TG_DIR)/FillDataFiles.o

$(TG_DIR)/TagGenTester.o: $(TG_DIR)/FillDataFiles.h $(TG_DIR)/TagGenTester.c $(SC_DIR)/SpecialConstants.h
	gcc $(FLAGS) $(TG_DIR)/TagGenTester.c -o $(TG_DIR)/TagGenTester.o

$(RD_DIR)/RetrievePokemon.o: $(RD_DIR)/RetrievePokemon.c $(RD_DIR)/RetrievePokemon.h $(SU_DIR)/Special_Util.h $(GD_DIR)/GlobalDestroyer.h $(SC_DIR)/SpecialConstants.h
	gcc $(FLAGS) $(RD_DIR)/RetrievePokemon.c -o $(RD_DIR)/RetrievePokemon.o

$(RD_DIR)/RetrieveTester.o: $(RD_DIR)/RetrieveTester.c $(RD_DIR)/RetrievePokemon.c $(RD_DIR)/RetrievePokemon.h $(SC_DIR)/SpecialConstants.h $(GD_DIR)/GlobalDestroyer.h
	gcc $(FLAGS) $(RD_DIR)/RetrieveTester.c -o $(RD_DIR)/RetrieveTester.o

$(BS_DIR)/BattleSimulation.o: $(BS_DIR)/BattleSimulation.c $(BS_DIR)/BattleSimulation.h $(RD_DIR)/RetrievePokemon.h  $(PE_DIR)/PokemonEntry.h $(GD_DIR)/GlobalDestroyer.h $(SC_DIR)/SpecialConstants.h $(SU_DIR)/Special_Util.h
	gcc $(FLAGS) $(BS_DIR)/BattleSimulation.c -o $(BS_DIR)/BattleSimulation.o

$(BS_DIR)/BattleSimTester.o: $(BS_DIR)/BattleSimTester.c $(BS_DIR)/BattleSimulation.h $(GD_DIR)/GlobalDestroyer.h 
	gcc $(FLAGS) $(BS_DIR)/BattleSimTester.c -o $(BS_DIR)/BattleSimTester.o

$(MT_DIR)/MoveTable.o: $(MT_DIR)/MoveTable.c $(SC_DIR)/SpecialConstants.h $(SU_DIR)/Special_Util.h
	gcc $(FLAGS) $(MT_DIR)/MoveTable.c -o $(MT_DIR)/MoveTable.o

$(MT_DIR)/MoveTableTester.o: $(MT_DIR)/MoveTableTester.c $(MT_DIR)/MoveTable.h $(SC_DIR)/SpecialConstants.h 
	gcc $(FLAGS) $(MT_DIR)/MoveTableTester.c -o $(MT_DIR)/MoveTableTester.o


clean: 
	rm */*.o *.o *~ PETester PokeMoveSetTester







